# -*- coding: utf-8 -*-
"""Crear csv con scrapping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KpyehNa6mtw-Ge-d_OiyTuFrLvczTUF8
"""

#BlocksMC

import pandas as pd

df = pd.read_html('https://es.wikipedia.org/wiki/Anexo:Gobernantes_de_Uruguay', parse_dates=True)

print(df[0].head(15))

df[0].to_csv('presidentes.csv')









