# -*- coding: utf-8 -*-
"""Regresión_lineal_simple.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ttkXq7zzdj6qS_R-2uVxj35-t1TP9Qz2
"""

#Una introducción a la regresión lineal

import pandas as pd
import numpy as np

DF = pd.read_csv('/content/Linear Regression - Sheet1.csv')

DF

DF.shape

Recordemos que en la regresión un cambio en la variable X causa un cambio en la variable Y

X=DF['X']
y=DF['Y']

from sklearn.linear_model import LinearRegression

model = LinearRegression()

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

X_train=np.array(X_train)
y_train=np.array(y_train)

model.fit(X_train.reshape(-1,1),y_train.reshape(-1,1))

model.score(X_train.reshape(-1,1),y_train.reshape(-1,1))

y_test=np.array(y_test)
X_test= np.array(X_test)

y_pred = model.predict(X_test.reshape(-1,1))

y_pred



import matplotlib.pyplot as plt

plt.scatter(y_test,y_pred)

Entendiendo X como horas dedicadas y Y como clasificación, la regresión muestra que a más horas más clasificación