# -*- coding: utf-8 -*-
"""SuperMarkets _Visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tnDxRvH5NYlnKBQSr9iuiHg1Skx44upS
"""

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
from plotnine import *
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

sample = pd.read_csv('/content/SampleSuperstore.csv')

sample.head()

sample.shape

sample.duplicated().sum()

sample.drop_duplicates(inplace = True)

sample.drop_duplicates(inplace = True)

sample.duplicated().sum()

col=['Postal Code']
sample1=sample.drop(columns=col,axis=1)

sample1.corr()

sample1.cov()

plt.figure(figsize=(16,8))
plt.bar('Sub-Category','Category', data=sample1)
plt.title('Category vs Sub Category')
plt.xlabel('Sub-Catgory')
plt.ylabel('Category')
plt.xticks(rotation=45)
plt.show()

sample1.columns.values

sample1['Ship Mode'].value_counts()

sample1['Segment'].value_counts()

sample1['Country'].value_counts()

sample1['State'].value_counts()

sample1['Region'].value_counts()

sample1['Category'].value_counts()

sample1['Sub-Category'].value_counts()

sample1['Quantity'].value_counts()

sample1['Discount'].value_counts()

sample.columns.values

plt.figure(figsize=(15,15))
sns.countplot(x=sample1['Ship Mode'])
plt.xticks(rotation=90)
plt.title("Ship")
plt.show()

plt.figure(figsize=(15,15))
sns.countplot(x=sample1['Segment'])
plt.xticks(rotation=90)
plt.title("Segment")
plt.show()

plt.figure(figsize=(15,15))
sns.countplot(x=sample1['Country'])
plt.xticks(rotation=90)
plt.title("Country")
plt.show()

plt.figure(figsize=(15,15))
sns.countplot(x=sample1['State'])
plt.xticks(rotation=90)
plt.title("STATE")
plt.show()

sample.columns.values

plt.figure(figsize=(15,15))
sns.countplot(x=sample1['Region'])
plt.xticks(rotation=90)
plt.title("Region")
plt.show()

plt.figure(figsize=(15,15))
sns.countplot(x=sample1['Category'])
plt.xticks(rotation=90)
plt.title("Category")
plt.show()

plt.figure(figsize=(15,15))
sns.countplot(x=sample1['Sub-Category'])
plt.xticks(rotation=90)
plt.title("sub-category")
plt.show()

plt.figure(figsize=(15,15))
sns.countplot(x=sample1['Quantity'])
plt.xticks(rotation=90)
plt.title("Quantity")
plt.show()

plt.figure(figsize=(15,15))
sns.countplot(x=sample1['Discount'])
plt.xticks(rotation=90)
plt.title("Discount")
plt.show()

sample.columns.values

Profit_plot = (ggplot(sample, aes(x='Ship Mode', y='Profit', fill='Sub-Category')) + geom_col() + coord_flip()
+ scale_fill_brewer(type='div', palette="Spectral") + theme_classic() + ggtitle('Pie Chart'))

display(Profit_plot)

Profit_plot = (ggplot(sample, aes(x='Segment', y='Profit', fill='Sub-Category')) + geom_col() + coord_flip()
+ scale_fill_brewer(type='div', palette="Spectral") + theme_classic() + ggtitle('Pie Chart'))

display(Profit_plot)

Profit_plot = (ggplot(sample, aes(x='Segment', y='Profit', fill='Sub-Category')) + geom_col() + coord_flip()
+ scale_fill_brewer(type='div', palette="Spectral") + theme_classic() + ggtitle('Pie Chart'))

display(Profit_plot)

Profit_plot = (ggplot(sample, aes(x='State', y='Profit', fill='Sub-Category')) + geom_col() + coord_flip()+ scale_fill_brewer(type='div', palette="Spectral") + theme_classic() + ggtitle('Pie Chart'))

display(Profit_plot)

Profit_plot = (ggplot(sample, aes(x='Region', y='Profit', fill='Sub-Category')) + geom_col() + coord_flip()
+ scale_fill_brewer(type='div', palette="Spectral") + theme_classic() + ggtitle('Pie Chart'))

display(Profit_plot)

Profit_plot = (ggplot(sample, aes(x='Sub-Category', y='Profit', fill='Sub-Category')) + geom_col() + coord_flip()
+ scale_fill_brewer(type='div', palette="Spectral") + theme_classic() + ggtitle('Pie Chart'))

display(Profit_plot)

Profit_plot = (ggplot(sample, aes(x='Category', y='Profit', fill='Sub-Category')) + geom_col() + coord_flip()
+ scale_fill_brewer(type='div', palette="Spectral") + theme_classic() + ggtitle('Pie Chart'))

display(Profit_plot)

Profit_plot = (ggplot(sample, aes(x='Quantity', y='Profit', fill='Sub-Category')) + geom_col() + coord_flip()
+ scale_fill_brewer(type='div', palette="Spectral") + theme_classic() + ggtitle('Pie Chart'))

display(Profit_plot)

Profit_plot = (ggplot(sample, aes(x='Discount', y='Profit', fill='Sub-Category')) + geom_col() + coord_flip()
+ scale_fill_brewer(type='div', palette="Spectral") + theme_classic() + ggtitle('Pie Chart'))

display(Profit_plot)



sample1.columns.values

ggplot(sample, aes(x='Ship Mode', fill = 'Category')) + geom_bar(stat = 'count')

ggplot(sample, aes(x='Segment', fill = 'Category')) + geom_bar(stat = 'count')

ggplot(sample, aes(x='Country', fill = 'Category')) + geom_bar(stat = 'count')

ggplot(sample, aes(x='Region', fill = 'Category')) + geom_bar(stat = 'count')

ggplot(sample, aes(x='Category', fill = 'Category')) + geom_bar(stat = 'count')

ggplot(sample, aes(x='Sub-Category', fill = 'Category')) + geom_bar(stat = 'count')

sample1.columns.values

ggplot(sample, aes(x='Quantity', fill = 'Category')) + geom_bar(stat = 'count')

ggplot(sample, aes(x='Discount', fill = 'Category')) + geom_bar(stat = 'count')

figsize=(15,10)
sns.pairplot(sample1,hue='Sub-Category')
plt.show